2024-02-05 16:30:15,558 ERROR: Exception on /edit_profile [POST] [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/routes.py", line 71, in edit_profile
    db.session.commit()
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 598, in commit
    return self._proxied.commit()
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1969, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1256, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1231, in _prepare_impl
    self.session.flush()
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
    self._flush(objects)
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4447, in _flush
    with util.safe_reraise():
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
    flush_context.execute()
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 910, in _emit_update_statements
    c = connection.execute(
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('funky2', "I'm funky biaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaatch", 2)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-03-25 17:05:47,640 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:05:48,065 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:06:10,639 INFO: funky logged in successfully [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/routes.py:33]
2024-03-25 17:06:41,838 INFO: funky tried logging in with invalid username or password [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/routes.py:26]
2024-03-25 17:06:51,890 INFO: funky logged in successfully [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/routes.py:33]
2024-03-25 17:09:46,643 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:10:55,070 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:12:09,457 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:12:33,885 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:32:27,826 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:32:28,325 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:33:06,433 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:36:01,074 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:36:56,322 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:42:02,741 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:44:49,254 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:45:30,338 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:50:35,109 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:50:49,022 INFO: users categories before ctegorize function: {'uncategorized': [6]} [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/routes.py:78]
2024-03-25 17:55:53,041 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:57:04,277 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:57:47,356 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 17:57:57,010 INFO: users categories before ctegorize function: {'uncategorized': [7]} [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/routes.py:78]
2024-03-25 18:53:39,031 INFO: users categories before ctegorize function: {'uncategorized': [8]} [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/routes.py:78]
2024-03-25 18:54:24,409 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 18:54:35,444 INFO: users categories before ctegorize function: {'uncategorized': [8], 'features': [9]} [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/routes.py:78]
2024-03-25 18:55:58,058 INFO: GidGud startup [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/__init__.py:65]
2024-03-25 18:56:07,476 INFO: users categories before ctegorize function: {'uncategorized': [10], 'features': [9]} [in /home/diza/Projects/VSCode_Projects/Myfuture/gid-gud/app/routes.py:78]
